# Dependabot configuration file
version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the `.github/workflows` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests for GitHub Actions dependencies
    open-pull-requests-limit: 10
    # Assign pull requests to repository owners
    assignees:
      - "tzok"
    # Add labels to pull requests
    labels:
      - "dependencies"
      - "github-actions"
    # Auto-merge non-major updates
    groups:
      github-actions:
        patterns:
          - "*"
    # Configure auto-merge for non-major updates
    auto-merge:
      # Only merge if the PR has been approved or if only dependency updates
      auto-approve: true
      # Only merge patch and minor version updates, not major
      allowed-update-types:
        - "minor"
        - "patch"
        
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "python"
    groups:
      python-packages:
        patterns:
          - "*"
    auto-merge:
      auto-approve: true
      allowed-update-types:
        - "minor"
        - "patch"
        
  # Enable version updates for Docker images in each tool directory
  - package-ecosystem: "docker"
    directory: "/fr3d/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "docker"
      
  - package-ecosystem: "docker"
    directory: "/maxit/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "docker"
      
  - package-ecosystem: "docker"
    directory: "/reduce/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "docker"
      
  - package-ecosystem: "docker"
    directory: "/rnaview/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "docker"
      
  - package-ecosystem: "docker"
    directory: "/rnapolis/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    assignees:
      - "tzok"
    labels:
      - "dependencies"
      - "docker"
