name: "rnapolis"
docker_image: "ghcr.io/tzok/cli2rest-rnapolis:latest"
cli_tool: "unifier-wrapper.py"
arguments:
  - "--format"
  - "PDB"
  - "input.tar.gz"
input_file: "input.tar.gz"
output_files:
  - "output.tar.gz"
