name: "rnapolis"
docker_image: "ghcr.io/tzok/cli2rest-rnapolis:latest"
cli_tool: "rnapolis"  # Assuming 'rnapolis' is the command-line tool
arguments:
  - "-i"
  - "input.cif"
  - "-o"
  - "output.json"
input_file: "input.cif"
output_files:
  - "output.json"
