name: "fr3d"
docker_image: "ghcr.io/tzok/cli2rest-fr3d:latest"
arguments:
  - "wrapper.py"
  - "input.cif"
input_file: "input.cif"
output_files:
  - "basepair_detail.txt"
  - "stacking.txt"
  - "backbone.txt"
