name: "maxit-pdb2cif"
description: "Convert PDB files to CIF format"
docker_image: "ghcr.io/tzok/cli2rest-maxit:latest"

inputs:
  - name: "input_file"
    description: "Input PDB file or directory containing PDB files"
    type: "file"
    required: true
    extensions: [".pdb"]

outputs:
  - name: "output_file"
    description: "Output CIF file"
    file_pattern: "{{ input_file_base }}.cif"

command:
  cli_tool: "maxit"
  template: "{{ cli_tool }} -input {{ input_file }} -output {{ output_file }} -o 1"
  file_mappings:
    - input: "{{ input_file }}"
      container_path: "input.pdb"
