tool: inkscape
image: ghcr.io/tzok/cli2rest-inkscape:latest
command:
  - inkscape
  - input.svg
  - --export-type=png
  - --export-filename=output.png
input_files:
  - filename: input.svg
    content: "{file_content}"
output_files:
  - output.png
