name: "inkscape"
docker_image: "ghcr.io/tzok/cli2rest-inkscape:latest"
arguments:
  - "inkscape"
  - "input.eps"
  - "--export-area-drawing"
  - "--export-plain-svg"
  - "--export-filename=output.svg"
input_file: "input.eps"
output_files:
  - "output.svg"
