tool: inkscape
image: ghcr.io/tzok/cli2rest-inkscape:latest
command:
  - inkscape
  - input.eps
  - --export-type=svg
  - --export-filename=output.svg
input_files:
  - filename: input.eps
    content: "{file_content}"
output_files:
  - output.svg
