name: Build and Push cli2rest-bpnet image

on:
  schedule:
    # Run daily at 1:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest BPNet commit
        id: get_version
        run: |
          # Get the latest commit hash from the BPNet repository
          LATEST_COMMIT=$(git ls-remote https://github.com/computational-biology/bpnet.git HEAD | cut -f1)
          echo "Latest BPNet commit: $LATEST_COMMIT"
          echo "version=$LATEST_COMMIT" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./bpnet
          push: ${{ github.event_name != 'pull_request' }}
          load: true
          tags: |
            ${{ github.event_name == 'pull_request' && format('ghcr.io/tzok/cli2rest-bpnet:test') || '' }}
            ghcr.io/tzok/cli2rest-bpnet:latest
            ghcr.io/tzok/cli2rest-bpnet:${{ github.sha }}
            ghcr.io/tzok/cli2rest-bpnet:${{ steps.get_version.outputs.version }}-${{ env.DATE }}
            ghcr.io/tzok/cli2rest-bpnet:${{ steps.get_version.outputs.version }}
          cache-from: type=gha,ref=ghcr.io/tzok/cli2rest-bpnet:latest
          cache-to: type=gha,mode=max

      - name: Test Docker image
        run: |
          docker run --name cli2rest-bpnet-test -d -p 8000 ghcr.io/tzok/cli2rest-bpnet:test
          sleep 5 # Wait for container to start
          HOST_PORT=$(docker port cli2rest-bpnet-test 8000 | cut -d: -f2)
          curl -s "http://localhost:$HOST_PORT/health" | grep '"status":"healthy"'

          pip install .
          curl -L -o 1ehz.pdb https://files.rcsb.org/download/1EHZ.pdb

          cli2rest-bio --api-url http://localhost:$HOST_PORT src/cli2rest_bio/configs/bpnet/config-pdb.yaml 1ehz.pdb

          for f in bpnet-1ehz-input.rob bpnet-1ehz-stdout.txt bpnet-1ehz-stderr.txt; do
            if [ ! -f "$f" ]; then
              echo "Test failed: Output file $f is missing."
              ls -l
              exit 1
            fi
          done
          echo "Test passed: All output files created."

          docker stop cli2rest-bpnet-test

